spring:
  #thymeleaf
  thymeleaf:
    prefix:
      classpath: /templates/
    suffix: .html
    cache: false
  #druid
  datasource:
    url: jdbc:mysql://192.168.25.132:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis
  redis:
    host: 192.168.25.132
    port: 6379
#    password: 123456
    timeout: 10
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500
  #static
  resources:
    add-mappings: true
    cache:
      period: 3600
    chain:
      cache: true
      enabled: true
      html-application-cache: true
    static-locations: classpath:/static/
  #rabbitmq
  rabbitmq:
    host: 192.168.25.132
    port: 5672
    username: guest
    password: guest
    virtual-host: /
    listener:
      direct:
        retry:
          max-attempts: 3
          enabled: true
          initial-interval: 1000
          multiplier: 1.0
      simple:
        auto-startup: true
        prefetch: 1
        concurrency: 10
        max-concurrency: 10
        default-requeue-rejected: true
#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        max-wait: 3s


#mybatis
mybatis:
  type-aliases-package: com.shm.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations:
    classpath: com.shm.miaosha.dao/*.xml
