spring:
  #thymeleaf
  thymeleaf:
    prefix:
      classpath: /templates/
    suffix: .html
  #druid
  datasource:
    url: jdbc:mysql://localhost:3306/miaosha?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: shm5555
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  #Redis
  redis:
    host: 192.168.25.132
    port: 6379
#    password: 123456
    timeout: 10
    poolMaxTotal: 1000
    poolMaxIdle: 500
    poolMaxWait: 500

#    jedis:
#      pool:
#        max-active: 10
#        max-idle: 10
#        max-wait: 3s


#mybatis
mybatis:
  type-aliases-package: com.shm.miaosha.domain
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations:
    classpath: com.shm.miaosha.dao/*.xml

